name: Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Webdriver Manager
      run: |
        python -c "from webdriver_manager.chrome import ChromeDriverManager; ChromeDriverManager().install()"

    - name: Run Robot Framework tests
      run: |
        robot -d results -v LOGINPAGE_URL:${{ secrets.LOGINPAGE_URL }} -v VALID_ORDERING_EMAIL:${{ secrets.VALID_ORDERING_EMAIL }} -v VALID_FORECASTING_EMAIL:${{ secrets.VALID_FORECASTING_EMAIL }} testsuites/Kadena_Tests.robot

    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: results/

    - name: Publish test results as a GitHub Pages site
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GH_PAGES_TOKEN }}
        external_repository: ${{ github.repository }}
        publish_dir: ./results/
        publish_branch: gh-pages 
        commit_message: "Publish Kadena Test Results"